---
- name: Add repo
  yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm state=present

- name: Install postgres
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - "postgresql96"
    - "postgresql96-server"
    - "postgresql96-contrib"
    - "python-psycopg2"

- name: Initialize data directory
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  ignore_errors: yes

- name: Start and enable the service
  service: name=postgresql-9.6 state=started enabled=yes
