---
- name: Add key for repo
  apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc" state=present

- name: Enable repo for postgresql
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" state=present filename="pgdg"

- name: Install postgres
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "postgresql-10"
    - "python-psycopg2"
