---
- name: Install nginx
  apt:
    state: present
    pkg:
      - nginx
      - certbot
      - python3-certbot-nginx

- name: Copy tls config snippets
  copy:
    src: tls.conf
    dest: /etc/nginx/snippets/tls.conf

- name: Copy header config snippets
  copy:
    src: headers.conf
    dest: /etc/nginx/snippets/headers.conf
