---
- block:
    - name: Install nginx
      apt: name=nginx state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
    - name: Install nginx
      yum: name=nginx state=present

    - name: git for ansible git module
      yum: name=git state=present

    - name: enable and start the service
      service: name=nginx state=started enabled=yes
  when: ansible_distribution == 'CentOS'

