version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    container_name: keycloak
    network_mode: host
    command:
      - start
      - '--auto-build'
    environment:
      - KC_DB=postgres
      - KC_FEATURES=token-exchange
      - KC_DB_URL=jdbc:postgresql://localhost/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=$KC_DB_PASSWORD
      - KC_HOSTNAME=$KC_HOSTNAME
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN=admin
    restart: unless-stopped

