---
- name: Template service file
  template:
    src: restic-backup.service.j2
    dest: /etc/systemd/system/restic-backup-{{ service_name }}.service

- name: Template timer file
  template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup-{{ service_name }}.timer

- name: Enable and start backup timer
  systemd:
    daemon_reload: true
    name: restic-backup-{{ service_name }}.timer
    enabled: true
    state: started
