- name: Install repo adding deps
  apt:
    pkg:
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - curl
    state: present

- name: Add key for surry repos
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /usr/share/keyrings/deb.sury.org-php.gpg

- name: Add surry php repos
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
