---
- name: add user
  user:
    name: cherrymusic
    home: /srv/cherrymusic

- name: get cherrymusic from git
  git:
    repo: https://github.com/devsnd/cherrymusic.git
    dest: /srv/cherrymusic/repo

- name: create config directory
  file:
    path: /srv/cherrymusic/.config/cherrymusic
    state: directory
    owner: cherrymusic
    group: cherrymusic

- name: create config file
  template:
    src: cherrymusic.conf.j2
    dest: /srv/cherrymusic/.config/cherrymusic/cherrymusic.conf
    owner: cherrymusic
    group: cherrymusic

- name: copy service file
  copy:
    src: cherrymusic.service
    dest: /etc/systemd/system
  notify: restart cherrymusic

- name: enable the service
  systemd:
    name: cherrymusic
    enabled: yes
    daemon_reload: yes
