---
- name: Install admin utilities
  package: name="{{ item }}" state=present
  with_items:
    - vim
    - htop
    - iotop
    - iftop
    - tmux
    - rsync
    - wget
    - mosh
    - lsof
    - curl
