---
- name: Install certbot
  apt:
    pkg:
      - certbot
      - python3-certbot-dns-cloudflare

- name: Create letsencrypt dir
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Certbot config for "{{ cert_toplevel_domain }}"
  template:
    src: dnscloudflare.ini.j2
    dest: /etc/letsencrypt/{{ cert_toplevel_domain }}.ini
    owner: root
    group: root
    mode: "0600"

- name: Generate certs for "{{ cert_toplevel_domain }}"
  command: certbot certonly --non-interactive --agree-tos --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/{{ cert_toplevel_domain }}.ini -m {{ certbot_email
    }} -d {{ cert_domains | join(' -d ') }}
  args:
    creates: /etc/letsencrypt/renewal/{{ cert_toplevel_domain }}.conf
