---
- name: Generate DH key
  command: openssl dhparam -out /etc/ssl/private/dhparam2048.pem 2048
  args:
    creates: /etc/ssl/private/dhparam2048.pem

- import_tasks: postfix.yml
  tags: [postfix]
- import_tasks: dovecot.yml
  tags: [dovecot]
- import_tasks: opendkim.yml
  tags: [opendkim]
- import_tasks: rspamd.yml
  tags: [rspamd]
