---
# Installs and configures the Rspamd spam filtering system.
- name: install apt-transport-https
  apt: name=apt-transport-https state=present

- name: Add rspamd GPG key
  get_url:
    url: https://rspamd.com/apt-stable/gpg.key
    dest: /etc/apt/keyrings/rspamd.asc
    mode: '0644'
    force: true

- name: Add Rspamd repository
  apt_repository: repo="deb [signed-by=/etc/apt/keyrings/rspamd.gpg] https://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"

- name: Install Rspamd and Redis
  apt:
    pkg: "{{ rspamd_packages }}"
    state: present
    update_cache: true
  vars:
    rspamd_packages:
      - rspamd
      - redis-server

- name: Make rspamd log to systemd journal
  copy: src=etc_rspamd_local.d_logging.inc dest=/etc/rspamd/local.d/ mode="0644"

- name: Start redis
  service: name=redis-server state=started

- name: Start rspamd systemd listener
  service: name=rspamd state=started
