---
- name: Install postgres
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "postgresql-11"
    - "python-psycopg2"

- set_fact: hashed_password="{{ [db_admin_password,db_admin_username] | join('') | md5  }}"

- name: setup db password
  postgresql_user:
    db: postgres
    name: postgres
    password: "{{ ['md5',hashed_password] | join('') }}"
    encrypted: yes
  become: true
  become_user: postgres
