---
- name: Install postgres and libraries
  apt:
    name:
      - postgresql
      - postgresql-common
      - python3-psycopg2
    state: present
    update_cache: true

- name: Set hashed password fact
  set_fact: hashed_password="{{ [db_admin_password,db_admin_username] | join('') | md5  }}"

- name: setup db password
  postgresql_user:
    db: postgres
    name: postgres
    password: "{{ ['md5',hashed_password] | join('') }}"
    encrypted: true
  become: true
  become_user: postgres
